//Найти максимальное из трех чисел
Console.Write("Введите первое число ");
string First_number = Console.ReadLine();
double number_first = Convert.ToDouble(First_number);
Console.Write("Введите второе число ");
string Second_number = Console.ReadLine();
double number_second = Convert.ToDouble(Second_number);
Console.Write("Введите третье число ");
string Third_number = Console.ReadLine();
double number_third = Convert.ToDouble(Third_number);
double max = number_first;
if (number_first > max) max = number_first;
if (number_second > max) max = number_second;
if (number_third > max) max = number_third;
Console.Write("max = ");
Console.WriteLine(max);

// Console.Write("Введите первое число ");
// string First_number = Console.ReadLine();
// float number_first = Convert.ToFloat(First_number);
// Console.Write("Введите второе число ");
// string Second_number = Console.ReadLine();
// float number_second = Convert.ToFloat(Second_number);
// Console.Write("Введите третье число ");
// string Third_number = Console.ReadLine();
// float number_third = Convert.ToFloat(Third_number);
// float max = number_first;
// if (number_first > max) max = number_first;
// if (number_second > max) max = number_second;
// if (number_third > max) max = number_third;
// Console.Write("max = ");
// Console.WriteLine(max);
